<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDVX0fKb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDVX0fKb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDVX0fKb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDVX0fKb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDVX0fKb\App_KernelDevDebugContainer([
    'container.build_hash' => 'DVX0fKb',
    'container.build_id' => 'cf4c1399',
    'container.build_time' => 1580664423,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDVX0fKb');
